"""Build a portable wake-word training bundle on a box that cannot train.

Training a custom openWakeWord phrase needs a CUDA GPU (synthetic-speech
generation + PyTorch, ~minutes-to-hours and ~12 GB of scratch). A CPU-only
desktop can still do the deterministic prep: pin the phrase and hyper-parameters,
render a ready-to-run trainer config + runner script, and pack them into one
archive. That archive is carried to a GPU box, which installs the heavy stack and
runs the training, then the resulting ``.onnx`` is carried back and registered
with ``kow-voice train <phrase> --model <file>``.

This module renders the bundle; it intentionally has no torch/openWakeWord
imports so it runs anywhere. The training recipe targets the maintained
``openwakeword-trainer`` pipeline (CUDA, torchaudio-2.10+ patches), with the
upstream ``openwakeword/train.py --training_config`` flow noted as a fallback.
"""

from __future__ import annotations

import json
import tarfile
from pathlib import Path

from .train import slugify

# GPU runner we drive on the training box (granular pipeline, applies the
# torchaudio/piper compatibility patches the upstream notebook now needs).
TRAINER_REPO = "https://github.com/lgpearson1771/openwakeword-trainer.git"

# Defaults for the openWakeWord training config; all overridable from the CLI.
DEFAULTS = {
    "n_samples": 50000,        # positive synthetic clips to generate
    "steps": 50000,            # training iterations
    "tts_batch_size": 25,      # lower if the GPU runs out of memory
    "layer_size": 32,          # classifier hidden width
    "target_fp_per_hour": 0.2,  # tuning target for false positives
    "sample_rate": 16000,
}


def build_spec(phrase: str, **overrides) -> dict:
    """The canonical, machine-readable description of one training job."""
    slug = slugify(phrase)
    spec = {
        "phrase": phrase.strip(),
        "slug": slug,
        "model_name": slug,
        "negatives": _default_negatives(phrase),
        "trainer_repo": TRAINER_REPO,
    }
    for key, value in DEFAULTS.items():
        spec[key] = overrides.get(key, value)
    # Keep only known overrides, ignore Nones so the CLI can pass them blindly.
    for key, value in overrides.items():
        if key in spec and value is not None:
            spec[key] = value
    return spec


def _default_negatives(phrase: str) -> list[str]:
    """Near-miss phrases the model should explicitly reject (cut false fires)."""
    base = phrase.strip().lower()
    near = {"kowalski": ["kowabunga", "kovalski", "kowalsky", "koala", "wciski"]}
    return near.get(base, [])


def render_config_yaml(spec: dict) -> str:
    """openWakeWord / openwakeword-trainer training config (configs/<slug>.yaml)."""
    negatives = "".join(f'  - "{n}"\n' for n in spec["negatives"]) or "  []\n"
    return (
        f"# openWakeWord training config for the '{spec['phrase']}' wake word.\n"
        f"# Generated by `kow-voice train {spec['phrase']} --prepare`; edit freely.\n"
        f'model_name: "{spec["model_name"]}"\n'
        "target_phrase:\n"
        f'  - "{spec["phrase"]}"\n'
        "custom_negative_phrases:\n"
        f"{negatives}"
        f"n_samples: {spec['n_samples']}\n"
        f"n_samples_val: {max(2000, spec['n_samples'] // 25)}\n"
        f"steps: {spec['steps']}\n"
        f"tts_batch_size: {spec['tts_batch_size']}\n"
        f"layer_size: {spec['layer_size']}\n"
        f"target_false_positives_per_hour: {spec['target_fp_per_hour']}\n"
    )


def render_train_sh(spec: dict) -> str:
    """The GPU-box runner: clone the trainer, install it, train, point at output."""
    slug = spec["slug"]
    return (
        "#!/usr/bin/env bash\n"
        f"# Train the '{spec['phrase']}' wake word on a CUDA GPU box. See README.md.\n"
        "# Needs: Linux/WSL2 + NVIDIA GPU + CUDA, Python >=3.10, git.\n"
        "set -euo pipefail\n"
        'HERE="$(cd "$(dirname "$0")" && pwd)"\n'
        f'REPO="${{OWW_TRAINER_REPO:-{spec["trainer_repo"]}}}"\n'
        "# Args are forwarded to train_wakeword.py, so a failed step resumes with the\n"
        "# full env set up: ./train.sh --from generate  (override work dir via WORK=...).\n"
        'WORK="${WORK:-$HERE/work}"\n'
        'echo "[kowalski-train] self-patching: piper-phonemize-fix, webrtcvad-wheels, '
        "scipy<1.17, piper-model-size, mit-rirs, config-merge, resumable-features, "
        'generate_samples-restore, torch-weights-only, gpu-auto(legacy-cu126/cpu)"\n'
        'echo "[kowalski-train] resume a failed step with:  ./train.sh --from <step>"\n'
        'mkdir -p "$WORK" && cd "$WORK"\n'
        '[ -d openwakeword-trainer ] || git clone --depth 1 "$REPO" openwakeword-trainer\n'
        "cd openwakeword-trainer\n"
        '[ -d .venv ] || python3 -m venv .venv\n'
        '. .venv/bin/activate\n'
        "pip install --upgrade pip\n"
        "# Some trainer deps lack cp312 wheels and would need a source build\n"
        "# (compiler + Python headers) or just fail; swap in prebuilt drop-in\n"
        "# repackages (same import names) so this needs no apt/build tools.\n"
        'PYVER="$(python -c \'import sys; print("%d.%d" % sys.version_info[:2])\')"\n'
        'if [ "$PYVER" = "3.12" ]; then\n'
        "  sed -i 's/^piper-phonemize>=.*/piper-phonemize-fix>=1.2.2/' requirements.txt\n"
        '  echo "Python 3.12 -> piper-phonemize-fix (cp312 wheels)"\n'
        "fi\n"
        "# webrtcvad has no cp312 wheel and needs Python.h to compile; the\n"
        "# webrtcvad-wheels fork ships prebuilt wheels (same 'webrtcvad' module).\n"
        "sed -i 's/^webrtcvad>=.*/webrtcvad-wheels>=2.0.14/' requirements.txt\n"
        'echo "using webrtcvad-wheels (prebuilt; no compiler/headers needed)"\n'
        "# acoustics (an openwakeword dep) imports scipy.special.sph_harm, removed in\n"
        "# SciPy 1.17; pin <1.17 so the function still exists (1.16 keeps numpy-2 compat).\n"
        "sed -i 's/^scipy$/scipy<1.17/' requirements.txt\n"
        "pip install -r requirements.txt\n"
        'python -c \'import piper_phonemize, webrtcvad\' || { echo '
        '"ERROR: a model dep did not import. See README.md (Python note); '
        'rebuilding .venv on Python 3.11 (rm -rf .venv && python3.11 -m venv '
        '.venv) is the usual fix."; exit 1; }\n'
        "# Build the training config by overriding the trainer's reference config\n"
        "# (configs/hey_echo.yaml) with our wake-word settings, so every infra key\n"
        "# the pipeline needs (paths, feature files, batch sizes) is inherited and\n"
        "# resolve-config never KeyErrors on a schema field we didn't ship.\n"
        f'python - "$HERE/{slug}.yaml" <<\'PYCFG\'\n'
        "import sys, yaml\n"
        'base = yaml.safe_load(open("configs/hey_echo.yaml"))\n'
        "ours = yaml.safe_load(open(sys.argv[1])) or {}\n"
        "base.update(ours)\n"
        f'with open("configs/{slug}.yaml", "w") as f:\n'
        "    yaml.safe_dump(base, f, sort_keys=False, allow_unicode=True)\n"
        'print("  config: wake-word settings merged onto the trainer reference config")\n'
        "PYCFG\n"
        "# The piper v2.0.0 voice asset is the complete ~204 MB file, but the\n"
        "# trainer's verify-data wrongly expects >=600 MB; relax that one threshold.\n"
        "sed -i 's/en_US-libritts_r-medium.pt\": 600_000_000/"
        "en_US-libritts_r-medium.pt\": 200_000_000/' train_wakeword.py\n"
        "# MIT RIRs load via a HF dataset script that new `datasets` rejects; pre-seed\n"
        "# data/mit_rirs from the repo wavs so verify-data passes (best effort — RIRs\n"
        "# are optional reverb augmentation).\n"
        'python - <<\'PYRIR\' || echo "  RIR prefetch skipped (training proceeds without reverb aug)"\n'
        "from huggingface_hub import snapshot_download\n"
        "import shutil, pathlib\n"
        'src = snapshot_download("davidscripka/MIT_environmental_impulse_responses",\n'
        '                        repo_type="dataset", allow_patterns="16khz/*.wav")\n'
        'dst = pathlib.Path("data/mit_rirs"); dst.mkdir(parents=True, exist_ok=True)\n'
        "n = 0\n"
        'for w in pathlib.Path(src, "16khz").glob("*.wav"):\n'
        "    shutil.copy(w, dst); n += 1\n"
        'print("  pre-seeded", n, "MIT RIR wavs")\n'
        "PYRIR\n"
        "# The trainer streams the ~16 GB ACAV100M feature file with no resume, so a\n"
        "# dropped connection restarts it from zero. Pre-fetch the big files with a\n"
        "# resumable downloader (the trainer then skips any dest that already exists).\n"
        "dl() {  # dl URL DESTDIR — resume + retry until the file is fully fetched\n"
        "  if command -v wget >/dev/null 2>&1; then\n"
        '    wget -c --tries=0 --timeout=60 --retry-connrefused -P "$2" "$1"\n'
        "  else\n"
        '    ( cd "$2" && until curl -fL -O -C - --retry 999 --retry-all-errors "$1"; do sleep 5; done )\n'
        "  fi\n"
        "}\n"
        'HF="https://huggingface.co/datasets/davidscripka/openwakeword_features/resolve/main"\n'
        "mkdir -p data\n"
        'ACAV="data/openwakeword_features_ACAV100M_2000_hrs_16bit.npy"\n'
        '[ -f "$ACAV.part" ] && mv -f "$ACAV.part" "$ACAV"  # reuse a trainer partial as the resume base\n'
        'dl "$HF/openwakeword_features_ACAV100M_2000_hrs_16bit.npy" data\n'
        'dl "$HF/validation_set_features.npy" data\n'
        "# THE generate-step fix. openWakeWord 0.6.0 does `from generate_samples import\n"
        "# generate_samples`, but rhasspy/piper-sample-generator master moved that\n"
        "# top-level script into a package, so the import fails outright (the file is\n"
        "# simply absent). Pre-clone the repo (master keeps the installable layout the\n"
        "# trainer's `pip install -e .` relies on) and restore generate_samples.py from\n"
        "# the v2.0.0 tag — the same release as the voice model — so the import resolves.\n"
        'PSG="data/piper-sample-generator"\n'
        "mkdir -p data\n"
        '[ -d "$PSG" ] || git clone --depth 1 https://github.com/rhasspy/piper-sample-generator.git "$PSG"\n'
        'if [ ! -f "$PSG/generate_samples.py" ]; then\n'
        '  echo "[kowalski-train] restoring generate_samples.py from piper-sample-generator@v2.0.0"\n'
        '  GS="https://raw.githubusercontent.com/rhasspy/piper-sample-generator/v2.0.0/generate_samples.py"\n'
        '  curl -fsSL -o "$PSG/generate_samples.py" "$GS" || wget -qO "$PSG/generate_samples.py" "$GS"\n'
        "fi\n"
        "# torch >=2.6 flipped torch.load's default to weights_only=True, which rejects\n"
        "# the full pickled Piper voice model; it's the official trusted model, so force\n"
        "# weights_only=False in the generator (idempotent; applied even on a re-run).\n"
        "[ -f \"$PSG/generate_samples.py\" ] && sed -i "
        "'s/torch.load(model_path)/torch.load(model_path, weights_only=False)/' "
        '"$PSG/generate_samples.py" || true\n'
        "# openWakeWord imports generate_samples from the repo root, so put it on PYTHONPATH.\n"
        'export PYTHONPATH="$PWD/$PSG${PYTHONPATH:+:$PYTHONPATH}"\n'
        "# ── GPU / torch selection ──────────────────────────────────────────────\n"
        "# An old GPU (e.g. Tesla P40 / Pascal sm_61) is absent from modern torch's\n"
        "# compiled kernels -> 'no kernel image is available'. Detect by launching a\n"
        "# real CUDA kernel; on failure swap to a cu126 torch build (still ships Pascal\n"
        "# sm_61) and retry; if still unusable (or no GPU) run on CPU. Override with\n"
        "# KOW_TRAIN_DEVICE=cpu|gpu and KOW_TRAIN_TORCH=auto|legacy|latest.\n"
        "gpu_probe() {\n"
        "  python - <<'PYP'\n"
        "try:\n"
        "    import torch\n"
        "    if not torch.cuda.is_available():\n"
        "        print('no_gpu')\n"
        "    else:\n"
        "        x = torch.zeros(8, device='cuda'); (x + 1).sum().item(); print('gpu_ok')\n"
        "except Exception:\n"
        "    print('gpu_bad')\n"
        "PYP\n"
        "}\n"
        "install_legacy_torch() {\n"
        '  echo "[kowalski-train] installing cu126 torch (ships Pascal sm_61) for this GPU…"\n'
        "  pip uninstall -y torch torchaudio >/dev/null 2>&1 || true\n"
        "  pip install --index-url https://download.pytorch.org/whl/cu126 torch torchaudio\n"
        "}\n"
        'TORCHSEL="${KOW_TRAIN_TORCH:-auto}"\n'
        'if [ "${KOW_TRAIN_DEVICE:-auto}" = "cpu" ]; then\n'
        '  export CUDA_VISIBLE_DEVICES=""\n'
        '  echo "[kowalski-train] KOW_TRAIN_DEVICE=cpu -> CPU"\n'
        "else\n"
        '  if [ "$TORCHSEL" = "legacy" ]; then install_legacy_torch || true; fi\n'
        '  PROBE="$(gpu_probe)"\n'
        '  if [ "$PROBE" = "gpu_bad" ] && [ "$TORCHSEL" = "auto" ]; then\n'
        '    echo "[kowalski-train] GPU present but unsupported by current torch — trying a cu126 build…"\n'
        "    install_legacy_torch || true\n"
        '    PROBE="$(gpu_probe)"\n'
        "  fi\n"
        '  if [ "$PROBE" = "gpu_ok" ]; then\n'
        '    echo "[kowalski-train] GPU OK — training on GPU."\n'
        '  elif [ "$PROBE" = "no_gpu" ]; then\n'
        '    echo "[kowalski-train] no CUDA GPU — training on CPU."\n'
        '    export CUDA_VISIBLE_DEVICES=""\n'
        "  else\n"
        '    echo "[kowalski-train] WARNING: GPU unusable (too old for available torch builds) — CPU fallback (slow; lower n_samples or use a CC>=7.5 GPU)."\n'
        '    export CUDA_VISIBLE_DEVICES=""\n'
        "  fi\n"
        "fi\n"
        f'python train_wakeword.py --config configs/{slug}.yaml "$@"\n'
        "# Pack the model (graph + its .onnx.data weights) into ONE archive so only\n"
        "# a single file travels back; kow-voice train --model unpacks it.\n"
        f'MODEL_FILES="{slug}.onnx"\n'
        f'[ -f "export/{slug}.onnx.data" ] && MODEL_FILES="$MODEL_FILES {slug}.onnx.data"\n'
        f'tar czf "$HERE/{slug}-model.tar.gz" -C export $MODEL_FILES\n'
        'echo\n'
        f'echo "Trained + packed: $HERE/{slug}-model.tar.gz"\n'
        f'echo "Carry that ONE file back, then on the Kowalski box run:"\n'
        f'echo "  kow-voice train {spec["phrase"]} --model {slug}-model.tar.gz"\n'
    )


def render_requirements(spec: dict) -> str:
    """Reference deps; train.sh installs the trainer's own requirements.txt."""
    return (
        "# Reference only — ./train.sh installs the trainer's pinned requirements.txt.\n"
        "# Listed so the heavy GPU stack is visible up front (CUDA wheels recommended):\n"
        "torch\n"
        "torchaudio\n"
        "openwakeword\n"
        "piper-tts\n"
        "speechbrain\n"
        "onnx\n"
        "onnxruntime\n"
        "soundfile\n"
        "numpy\n"
    )


def render_readme(spec: dict) -> str:
    """Human-facing scheme + the exact GPU-box and register-back commands."""
    slug = spec["slug"]
    return (
        f"# Wake-word training bundle — '{spec['phrase']}'\n\n"
        "Three stages, two machines.\n\n"
        "```\n"
        " [this CPU box]            [GPU box, CUDA]              [this CPU box]\n"
        " kow-voice train \\         ./train.sh                  kow-voice train \\\n"
        f"   {spec['phrase']} --prepare   ->  (clone trainer, install,   ->    {spec['phrase']} \\\n"
        f"   = THIS bundle              generate, train, pack)      --model {slug}-model.tar.gz\n"
        f"                            -> {slug}-model.tar.gz        = wired into kowalski.conf\n"
        "```\n\n"
        "## Stage 2 — on the GPU box\n\n"
        "Copy this whole folder over, then:\n\n"
        "```sh\n"
        "./train.sh                 # clones openwakeword-trainer, installs, trains\n"
        "```\n\n"
        "`train.sh` handles the venv, dependency swaps and PYTHONPATH itself — never\n"
        "activate anything by hand. If a step fails, fix it and **resume by re-running\n"
        "with the step it printed**, e.g. `./train.sh --from generate` (args pass\n"
        "straight through to `train_wakeword.py`; the early cached steps are fast). To\n"
        "pick up a newer bundle, unpack it from the PARENT dir (`cd ~ && tar xzf "
        "kowalski-wakeword-train.tar.gz`) so `train.sh` is overwritten in place while\n"
        "`work/` (the multi-GB downloads) is kept.\n\n"
        f"Tunables live in `{slug}.yaml` (`n_samples`, `steps`, `tts_batch_size`,\n"
        "`custom_negative_phrases`, `target_false_positives_per_hour`). Training takes\n"
        "minutes-to-hours and ~12 GB of scratch; a CUDA GPU is required.\n\n"
        "Python note: a couple of trainer deps lack cp312 wheels, so `train.sh`\n"
        "auto-swaps them for prebuilt drop-ins (same import names): on Python 3.12\n"
        "`piper-phonemize` -> `piper-phonemize-fix`, and always `webrtcvad` ->\n"
        "`webrtcvad-wheels` (otherwise webrtcvad compiles from source and needs\n"
        "`python3-dev`). It then verifies they import; if that fails, rebuild the\n"
        "venv on Python 3.11 and re-run.\n\n"
        "Data note: `train.sh` also relaxes the trainer's over-strict piper-model\n"
        "size check (the v2.0.0 asset is the complete ~204 MB file, not 600 MB) and\n"
        "pre-seeds the MIT RIRs straight from HuggingFace, because their dataset\n"
        "load script no longer works with current `datasets`. It also pre-fetches\n"
        "the ~16 GB ACAV100M feature file with a resumable downloader, so a dropped\n"
        "connection resumes instead of restarting the trainer's no-resume stream.\n\n"
        f"Output: `train.sh` trains `export/{slug}.onnx` (~14 KB graph) + "
        f"`export/{slug}.onnx.data`\n(~200 KB weights) and packs **both** into a single "
        f"`{slug}-model.tar.gz` in this\nfolder — that one archive is all you carry back.\n\n"
        "Fallback runner (upstream, currently fragile — see openWakeWord issue #296):\n"
        "`python openwakeword/train.py --training_config <yaml> --generate_clips "
        "--augment_clips --train_model --convert_to_tflite`.\n\n"
        "## Stage 3 — back on the Kowalski box\n\n"
        f"Copy the single `{slug}-model.tar.gz` over, then:\n\n"
        "```sh\n"
        f"kow-voice train {spec['phrase']} --model {slug}-model.tar.gz\n"
        "```\n\n"
        f"(A bare `{slug}.onnx` + `{slug}.onnx.data` pair still works too.) "
        f"That copies the model into `~/.config/kowalski/wake/` and sets "
        "`KOW_WAKE_MODEL` + `KOW_WAKE_MODE=both`, so `kow-voice run` / `kow chat "
        "--voice` answer to the spoken phrase. `spec.json` records the exact "
        "parameters this bundle was built with.\n"
    )


def _normalize(ti: tarfile.TarInfo) -> tarfile.TarInfo:
    """Strip every nondeterministic field from a tar entry (mtime, owner, and the
    umask-dependent mode) so the archive is reproducible across runs and boxes."""
    ti.mtime = 0
    ti.uid = ti.gid = 0
    ti.uname = ti.gname = ""
    is_script = ti.name.rsplit("/", 1)[-1] == "train.sh"
    ti.mode = 0o755 if (ti.isdir() or is_script) else 0o644
    return ti


def write_targz(tar_path: Path, bundle: Path, names: list[str]) -> None:
    """Write a byte-for-byte reproducible .tar.gz: identical content -> identical
    md5. gzip's header timestamp is zeroed and members are added in sorted order
    with normalized metadata, so the checksum tracks content only."""
    import gzip

    with open(tar_path, "wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as gz:
            with tarfile.open(fileobj=gz, mode="w") as tar:
                tar.add(bundle, arcname=bundle.name, recursive=False, filter=_normalize)
                for name in sorted(names):
                    tar.add(bundle / name, arcname=f"{bundle.name}/{name}", filter=_normalize)


def write_bundle(phrase: str, *, out_dir: Path | None = None, archive: bool = True,
                 **overrides) -> Path:
    """Render every artifact into a folder; optionally tar it. Returns the path."""
    spec = build_spec(phrase, **overrides)
    slug = spec["slug"]
    base = Path(out_dir).expanduser() if out_dir else Path.cwd()
    bundle = base / f"{slug}-wakeword-train"
    bundle.mkdir(parents=True, exist_ok=True)

    files = {
        "spec.json": json.dumps(spec, indent=2, ensure_ascii=False) + "\n",
        f"{slug}.yaml": render_config_yaml(spec),
        "train.sh": render_train_sh(spec),
        "requirements-train.txt": render_requirements(spec),
        "README.md": render_readme(spec),
    }
    for name, content in files.items():
        path = bundle / name
        path.write_text(content)
    (bundle / "train.sh").chmod(0o755)

    if not archive:
        return bundle
    tar_path = base / f"{slug}-wakeword-train.tar.gz"
    write_targz(tar_path, bundle, list(files))
    return tar_path
