"""Build a portable wake-word training bundle on a box that cannot train.

Training a custom openWakeWord phrase needs a CUDA GPU (synthetic-speech
generation + PyTorch, ~minutes-to-hours and ~12 GB of scratch). A CPU-only
desktop can still do the deterministic prep: pin the phrase and hyper-parameters,
render a ready-to-run trainer config + runner script, and pack them into one
archive. That archive is carried to a GPU box, which installs the heavy stack and
runs the training, then the resulting ``.onnx`` is carried back and registered
with ``kow-voice train <phrase> --model <file>``.

This module renders the bundle; it intentionally has no torch/openWakeWord
imports so it runs anywhere. The training recipe targets the maintained
``openwakeword-trainer`` pipeline (CUDA, torchaudio-2.10+ patches), with the
upstream ``openwakeword/train.py --training_config`` flow noted as a fallback.
"""

from __future__ import annotations

import json
import tarfile
from pathlib import Path

from .train import slugify

# GPU runner we drive on the training box (granular pipeline, applies the
# torchaudio/piper compatibility patches the upstream notebook now needs).
TRAINER_REPO = "https://github.com/lgpearson1771/openwakeword-trainer.git"

# Defaults for the openWakeWord training config; all overridable from the CLI.
DEFAULTS = {
    "n_samples": 50000,        # positive synthetic clips to generate
    "steps": 50000,            # training iterations
    "tts_batch_size": 25,      # lower if the GPU runs out of memory
    "layer_size": 32,          # classifier hidden width
    "target_fp_per_hour": 0.2,  # tuning target for false positives
    "sample_rate": 16000,
}


def build_spec(phrase: str, **overrides) -> dict:
    """The canonical, machine-readable description of one training job."""
    slug = slugify(phrase)
    spec = {
        "phrase": phrase.strip(),
        "slug": slug,
        "model_name": slug,
        "negatives": _default_negatives(phrase),
        "trainer_repo": TRAINER_REPO,
    }
    for key, value in DEFAULTS.items():
        spec[key] = overrides.get(key, value)
    # Keep only known overrides, ignore Nones so the CLI can pass them blindly.
    for key, value in overrides.items():
        if key in spec and value is not None:
            spec[key] = value
    return spec


def _default_negatives(phrase: str) -> list[str]:
    """Near-miss phrases the model should explicitly reject (cut false fires)."""
    base = phrase.strip().lower()
    near = {"kowalski": ["kowabunga", "kovalski", "kowalsky", "koala", "wciski"]}
    return near.get(base, [])


def render_config_yaml(spec: dict) -> str:
    """openWakeWord / openwakeword-trainer training config (configs/<slug>.yaml)."""
    negatives = "".join(f'  - "{n}"\n' for n in spec["negatives"]) or "  []\n"
    return (
        f"# openWakeWord training config for the '{spec['phrase']}' wake word.\n"
        f"# Generated by `kow-voice train {spec['phrase']} --prepare`; edit freely.\n"
        f'model_name: "{spec["model_name"]}"\n'
        "target_phrase:\n"
        f'  - "{spec["phrase"]}"\n'
        "custom_negative_phrases:\n"
        f"{negatives}"
        f"n_samples: {spec['n_samples']}\n"
        f"n_samples_val: {max(2000, spec['n_samples'] // 25)}\n"
        f"steps: {spec['steps']}\n"
        f"tts_batch_size: {spec['tts_batch_size']}\n"
        f"layer_size: {spec['layer_size']}\n"
        f"target_false_positives_per_hour: {spec['target_fp_per_hour']}\n"
    )


def render_train_sh(spec: dict) -> str:
    """The GPU-box runner: clone the trainer, install it, train, point at output."""
    slug = spec["slug"]
    return (
        "#!/usr/bin/env bash\n"
        f"# Train the '{spec['phrase']}' wake word on a CUDA GPU box. See README.md.\n"
        "# Needs: Linux/WSL2 + NVIDIA GPU + CUDA, Python >=3.10, git.\n"
        "set -euo pipefail\n"
        'HERE="$(cd "$(dirname "$0")" && pwd)"\n'
        f'REPO="${{OWW_TRAINER_REPO:-{spec["trainer_repo"]}}}"\n'
        'WORK="${1:-$HERE/work}"\n'
        'mkdir -p "$WORK" && cd "$WORK"\n'
        '[ -d openwakeword-trainer ] || git clone --depth 1 "$REPO" openwakeword-trainer\n'
        "cd openwakeword-trainer\n"
        '[ -d .venv ] || python3 -m venv .venv\n'
        '. .venv/bin/activate\n'
        "pip install --upgrade pip\n"
        "pip install -r requirements.txt\n"
        f'cp "$HERE/{slug}.yaml" "configs/{slug}.yaml"\n'
        f"python train_wakeword.py --config configs/{slug}.yaml\n"
        'echo\n'
        f'echo "Trained: $PWD/export/{slug}.onnx (+ {slug}.onnx.data)"\n'
        f'echo "Copy BOTH files back, then on the Kowalski box run:"\n'
        f'echo "  kow-voice train {spec["phrase"]} --model {slug}.onnx"\n'
    )


def render_requirements(spec: dict) -> str:
    """Reference deps; train.sh installs the trainer's own requirements.txt."""
    return (
        "# Reference only — ./train.sh installs the trainer's pinned requirements.txt.\n"
        "# Listed so the heavy GPU stack is visible up front (CUDA wheels recommended):\n"
        "torch\n"
        "torchaudio\n"
        "openwakeword\n"
        "piper-tts\n"
        "speechbrain\n"
        "onnx\n"
        "onnxruntime\n"
        "soundfile\n"
        "numpy\n"
    )


def render_readme(spec: dict) -> str:
    """Human-facing scheme + the exact GPU-box and register-back commands."""
    slug = spec["slug"]
    return (
        f"# Wake-word training bundle — '{spec['phrase']}'\n\n"
        "Three stages, two machines.\n\n"
        "```\n"
        " [this CPU box]            [GPU box, CUDA]              [this CPU box]\n"
        " kow-voice train \\         ./train.sh                  kow-voice train \\\n"
        f"   {spec['phrase']} --prepare   ->  (clone trainer, install,   ->    {spec['phrase']} \\\n"
        f"   = THIS bundle              generate + train)            --model {slug}.onnx\n"
        f"                            -> export/{slug}.onnx(.data)   = wired into kowalski.conf\n"
        "```\n\n"
        "## Stage 2 — on the GPU box\n\n"
        "Copy this whole folder over, then:\n\n"
        "```sh\n"
        "./train.sh                 # clones openwakeword-trainer, installs, trains\n"
        "```\n\n"
        f"Tunables live in `{slug}.yaml` (`n_samples`, `steps`, `tts_batch_size`,\n"
        "`custom_negative_phrases`, `target_false_positives_per_hour`). Training takes\n"
        "minutes-to-hours and ~12 GB of scratch; a CUDA GPU is required.\n\n"
        f"Output: `export/{slug}.onnx` (~14 KB graph) **and** `export/{slug}.onnx.data`\n"
        "(~200 KB weights). **Keep both together** — the model is split across them.\n\n"
        "Fallback runner (upstream, currently fragile — see openWakeWord issue #296):\n"
        "`python openwakeword/train.py --training_config <yaml> --generate_clips "
        "--augment_clips --train_model --convert_to_tflite`.\n\n"
        "## Stage 3 — back on the Kowalski box\n\n"
        f"Copy `{slug}.onnx` **and** `{slug}.onnx.data` into the same folder, then:\n\n"
        "```sh\n"
        f"kow-voice train {spec['phrase']} --model {slug}.onnx\n"
        "```\n\n"
        f"That copies the model into `~/.config/kowalski/wake/` and sets "
        "`KOW_WAKE_MODEL` + `KOW_WAKE_MODE=both`, so `kow-voice run` / `kow chat "
        "--voice` answer to the spoken phrase. `spec.json` records the exact "
        "parameters this bundle was built with.\n"
    )


def write_bundle(phrase: str, *, out_dir: Path | None = None, archive: bool = True,
                 **overrides) -> Path:
    """Render every artifact into a folder; optionally tar it. Returns the path."""
    spec = build_spec(phrase, **overrides)
    slug = spec["slug"]
    base = Path(out_dir).expanduser() if out_dir else Path.cwd()
    bundle = base / f"{slug}-wakeword-train"
    bundle.mkdir(parents=True, exist_ok=True)

    files = {
        "spec.json": json.dumps(spec, indent=2, ensure_ascii=False) + "\n",
        f"{slug}.yaml": render_config_yaml(spec),
        "train.sh": render_train_sh(spec),
        "requirements-train.txt": render_requirements(spec),
        "README.md": render_readme(spec),
    }
    for name, content in files.items():
        path = bundle / name
        path.write_text(content)
    (bundle / "train.sh").chmod(0o755)

    if not archive:
        return bundle
    tar_path = base / f"{slug}-wakeword-train.tar.gz"
    with tarfile.open(tar_path, "w:gz") as tar:
        tar.add(bundle, arcname=bundle.name)
    return tar_path
